### PR TITLE
Add proper support for standard HTTP methods (#974)

### PR DESCRIPTION
**Pull request by Bisk1**

### CODE REVIEW

**Comment by johanhaleby** [comment]
Thanks! There are some tests that are failing though. Is this expected with your change?

**Comment by Bisk1** [comment]
@johanhaleby No, I will check it

**Comment by Bisk1** [comment]
@johanhaleby  This is my second attempt -  I changed 3 public methods of HTTPBuilder - is it part of public API?

**Comment by johanhaleby** [comment]
> @johanhaleby This is my second attempt - I changed signature of 3 public methods of HTTPBuilder - is it part of public API?

No it shouldn't be (since it's located in the "internal" package).

Thanks again for the update. I'll try to look into it when I have to opportunity.

**Comment by johanhaleby** [comment]
I've look into the PR now and it looks good as far as I can tell but I still need to understand what problems we're solving here. Is it https://github.com/rest-assured/rest-assured/issues/974 specifically or does this solves even more problems? 

And you're right that it's by design that REST Assured supports sending body's in for all HTTP methods (including GET) since many people have asked for it for testing purposes.

**Comment by johanhaleby** [comment]
That's great! Thanks for the clarification and big thanks for the pull request and for helping out!

**Pull request merged**
