### PR TITLE
Spring MVC Test cases with Binary Data download fixed

### PR DESCRIPTION
**Pull request by sbespalov**

### CODE REVIEW

**Comment by johanhaleby** [comment]
Thanks for your help. Since the tests are still passing I assume that the fix is still backward compatible?

**Comment by sbespalov** [comment]
hope so.
I do not see any problems with this fix, only happiness for people who
reached this bug. :)

2017-01-18 13:28 GMT+07:00 Johan Haleby <notifications@github.com>:

**Comment by johanhaleby** [comment]
hehe ok! I'll merge it and publish a new snapshot.

**Comment by sbespalov** [comment]
SNAPSHOT will be available [here](https://oss.sonatype.org/content/repositories/snapshots/io/rest-assured/spring-mock-mvc/)?

**Comment by sbespalov** [comment]
SNAPSHOT will be available [here](https://oss.sonatype.org/content/repositories/snapshots/io/rest-assured/spring-mock-mvc/)?

**Comment by johanhaleby** [comment]
I've published the snapshot now. Please try version `3.0.2-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by sbespalov** [comment]
Excellent!
Many thanks!

**Comment by carlspring** [comment]
@johanhaleby,

Thanks for accepting this pull! Do you you know when 3.0.2 will be released?

**Comment by johanhaleby** [comment]
Nope, but I really ought to do it soon! There are many things I'd like to fix but maybe I should just release a minor version before taking on more things.

**Pull request merged**
