### PR TITLE
Replaced deprecated HttpMethod.resolve (#1760)

### PR DESCRIPTION
**Pull request by felhag**

### CODE REVIEW

**Comment by d0vi** [comment]
Duplicate of #1767.

**Comment by d0vi** [comment]
> @d0vi , it's not, it's a different file. Kinda looks you tried to update your PR yesterday (which is fine I guess) but it still only contains `MockMvcRequestSenderImpl` and not `WebTestClientRequestSenderImpl`.

Yeah, I updated the commit message adding the issue my commit is meant to close.
After looking at the files we are fixing, it looks like both PRs are complementary! 👌🏻

**Comment by johanhaleby** [comment]
@d0vi Is this ready to be merged?

**Comment by d0vi** [comment]
Hi @johanhaleby, thank you for merging this PR by @felhag. Cheers! 🎉
However, this only fixes the issue for the Spring Web Test Client module. Spring Mock Mvc module needs #1767 to properly work with Spring Framework 6.1+.

**Pull request merged**
