### PR TITLE
Fixes #1577 - Added support for ?., *. and ?[ to rootPath

### LINKED ISSUE #1577: rootPath does not allow chaining paths with leading operators
Assume we have endpoint `/` that returns:
```json
{"data": [
  {
    "foo": 123,
    "bar": 456,
    "baz": [
      {"a": 1, "c": 5},
      {"b": 2},
      {"a": 3, "b": 4}
    ]
  },
  {}
]}
```

What works:
```java
when()
  .get("/")
.then()
  .rootPath("data")
  .body("foo", is(123)) // ok
  .body(".bar", is(456)) // ok

  .rootPath("data.")
  .body("foo", is(123)) // ok
  .body(".bar", is(456)) // ok
  
  .appendRootPath("[0].baz")
  .body("[0].a", is(1)) // ok

  .rootPath("data[0].baz[1]")
  .body("b", is(2)); // ok
```

And what does not, but expected to work:

```java
// ... when.get.then yada yada
  .rootPath("data[0].baz")
  // Unexpected input - data[0].baz.?.size()
  //                               ^
  .body("?.size()", is(3))

  // Unexpected input - data[0].baz.*.subMap('a', 'b')*.values().flatten()
  //                               ^
  .body("*.subMap('a', 'b')*.values().flatten()")
  
  .rootPath("data[1].baz")
  
    // Unexpected input - data[0].baz.?[0].c
    //                               ^
  .body("?[0].c", is(999));
```

Obviously, `rootPath` and `body` checks whether dots/brackets is present in the beginning/end of path.
But safe-dereferencing `?.`, spread `*.` and safe index `?[]` operators are ignored and glue dot is added.

### PR DESCRIPTION
**Pull request by mitasov-ra**
Fixes #1577

Slightly modified `mergeKeyWithRootPath` function so it would not add dot between root path and key if key starts with `?.`, '?[' or `*.`.

Updated tests

### CODE REVIEW

**Comment by mitasov-ra** [comment]
Unfortunately I wasn't able to run build and tests locally due some complicated issues with Maven. So I really hope we can run them here, in Actions, or someone with working local build can run them for me.

This project really lacks something like Contribution guide btw.

**Comment by dilhelh** [comment]
@mitasov-ra, I get the build and tests to work inside the Intellij.

**Comment by mitasov-ra** [comment]
@dilhelh Thanks! So, it can be merged now?

**Comment by dilhelh** [comment]
> @dilhelh Thanks! So, it can be merged now?

I can't. Sorry @mitasov-ra, but I am not the maintainer of this project. Maybe @johanhaleby would help you out with that.

**Comment by johanhaleby** [comment]
Thank you!

**Pull request merged**
