### PR TITLE
Add additional check for parameters update

### PR DESCRIPTION
**Pull request by britka**
This check is needed when map of parameters contains collection as value

### CODE REVIEW

**Comment by johanhaleby** [comment]
Could you add a test as well to show the bug?

**Comment by britka** [comment]
Yes sure

**Comment by britka** [comment]
By the way this pull request should fix #787 issue. 
I'll prepare test and commit once again.

**Comment by johanhaleby** [comment]
Please do that, a test would be very helpful to both demonstrate the issue and to make sure that it won't happen again.

**Comment by britka** [comment]
Could you check my pull request please. 
If you have any question please feel free to ask them.

**Comment by johanhaleby** [comment]
Thanks! 👍

**Comment by britka** [comment]
Welcome

**Pull request merged**
