### PR TITLE
#679: Add on fail message builder for response specification

### PR DESCRIPTION
**Pull request by Frechet**
This is useful when you need to associate a mismatch description with additional user information. For example, in parallel execution.

### CODE REVIEW

**Comment by johanhaleby** [comment]
Is it important that the failure message is a part of the AssertionError? 

I've made some changes where I'm using a [ResponseValidationFailureListener](http://static.javadoc.io/io.rest-assured/rest-assured/3.3.0/io/restassured/listener/ResponseValidationFailureListener.html) to print the error message instead. I like the idea that we're building on existing building blocks (`ResponseValidationFailureListener` in this case) instead of implementing completely new concepts. On my machine it now looks like this:

image

However since `describedAs` is a part of the AssertionError it probably makes more sense the way you did it. Just want to hear your thoughts.

**Comment by Frechet** [comment]
@johanhaleby Thank you so much for your quick feedback!

> Is it important that the failure message is a part of the AssertionError?

I think, yes. I will try to explain why.
I looked at your proposed solution. Unfortunately, it cannot solve our problem. The fact is that in the ResponseValidationFailureListener we can write to the stream, but this will also be independent of the assertion written to the stream, as if we had written something like this:

```
log.info("test1");
response.then().statusCode(200)
--
[TestNG-tests-3] INFO test1
[TestNG-tests-2] INFO test3
// Here ResponseValidationFailureListener wrote something, but we cannot know it for this assert or another.
[TestNG-tests-4] INFO test2
...
java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.
[TestNG-tests-7] INFO test12
```

**Comment by mih-kopylov** [comment]
@johanhaleby any chance to have this PR merged?

**Comment by hasanalpzengin** [comment]
Important feature. What's status ? Do you need testers here ?

**Comment by MRC81** [comment]
I guess many would be happy to have this feature! Any chances to see it merged?

**Comment by cheparsky** [comment]
@johanhaleby maybe it is a good time to merge it? :) Do you need some testers or help?

**Comment by cheparsky** [comment]
@Frechet There is a conflict, please resolve it, maybe after that @johanhaleby merge it

**Comment by Frechet** [comment]
Hello everybody! Thanks for your feedback! I will try to resolve the conflict as soon as possible and ask for a merge.

**Comment by Frechet** [comment]
@cheparsky , @johanhaleby resolved conflicts https://github.com/rest-assured/rest-assured/pull/1502

**Pull request closed without merging**
