### PR TITLE
Make output of multiparts prettier

### PR DESCRIPTION
**Pull request by RocketRaccoon**
Currently multipart output is hard to read
```
Path params:	<none>
Multiparts:		controlName=json, mimeType=application/json, charset=<none>, fileName=file, content={...}
				controlName=content0, mimeType=application/octet-stream, charset=<none>, fileName=filename.txt, content=<inputstream>
				controlName=content1, mimeType=application/octet-stream, charset=<none>, fileName=filename.txt, content=<inputstream>
				controlName=content2, mimeType=application/octet-stream, charset=<none>, fileName=filename.txt, content=<inputstream>
Headers:		Accept=*/*
```

With fix
```
Headers:		Accept=*/*
Cookies:

Multiparts:
------------
Content-Disposition: form-data; name = json; filename = file
Content-Type: application/json
{...}
------------
Content-Disposition: form-data; name = content0; filename = filename.txt
Content-Type: application/octet-stream
<inputstream>
------------
Content-Disposition: form-data; name = content1; filename = filename.txt
Content-Type: application/octet-stream
<inputstream>
------------
Content-Disposition: form-data; name = content2; filename = filename.txt
Content-Type: application/octet-stream
<inputstream>
Body:
```

### CODE REVIEW

**Comment by RocketRaccoon** [comment]
looks like some tests should be fixed if this change is ok in general

**Comment by johanhaleby** [comment]
Thanks, the tests are all related to logging as far as I can tell.

**Comment by RocketRaccoon** [comment]
So, it fixed at last

**Comment by johanhaleby** [comment]
I've not forgotten about this. My plan is to indent the multipart logging so that's why I haven't merged it yet.

**Comment by RocketRaccoon** [comment]
Yeap ok, I have just prepared another pull request, and wrongly pushed it to here

**Pull request merged**
