### PR TITLE
 #858: CharSequence rather than String

### PR DESCRIPTION
**Pull request by weaselmetal**
Here's my PR for #858

### CODE REVIEW

**Comment by johanhaleby** [comment]
Oh it wasn't as hard as I expected. Thanks for doing this!

**Comment by johanhaleby** [comment]
@weaselmetal It turns out that this commit is not binary compatible (only source compatible) so I was forced to revert it.

Since this change is (unfortunately) backward incompatible it'll probably have to wait until the next major release before we can merge it again.

**Comment by weaselmetal** [comment]
SAD!On Oct 5, 2017 20:12, Johan Haleby <notifications@github.com> wrote:@weaselmetal It turns out that this commit is not binary compatible (only source compatible) so I was forced to revert it.
Since this change is (unfortunately) backward incompatible it'll probably have to wait until the next major release before we can merge it again.

**Comment by johanhaleby** [comment]
Sorry :( Thanks for the effort anyways

**Comment by weaselmetal** [comment]
No worries :). Keeping my `toString()` around ain't gonna kill me.

**Pull request merged**
