### PR TITLE
Added ability to order filters

### PR DESCRIPTION
**Pull request by jcravi**
Please let me know if I need more tests (and where?)

### CODE REVIEW

**Comment by johanhaleby** [comment]
Thanks a lot for the PR! I'll try to review it soon.

**Comment by johanhaleby** [comment]
Looks good to me! I'll probably add a bit more javadoc. Thanks a lot, good feature.

**Comment by johanhaleby** [comment]
I've refactored this somewhat. Sorting is lazy for example, will that have any negative impact that you're aware of?

**Comment by jcravi** [comment]
That's great! Thanks. The only negative I can think of right now is the performance, but I doubt that will be noticeable unless someone has upwards of a 100 filters. I would have preferred to create a sorted list, but since that doesn't exist, a treeset with a comparator. Also, if we could've have used java 8, default methods in interfaces.
I wanted to minimize what I was changing, since I don't fully understand the code yet.

**Comment by johanhaleby** [comment]
Yeah I doubt that it'll have any noticeable performance impacts. It would be great if you could try out the latest snapshot (version `3.0.2-SNAPSHOT`) to verify that it works for you after having added to following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by jcravi** [comment]
I will check it out today.

**Comment by jcravi** [comment]
Apologies for taking so long. I will try to get this done sooner rather than later.

**Comment by jcravi** [comment]
Alright, I was able to test it out with our scenario and it worked perfectly. Thanks again for the quick turnaround @johanhaleby!

**Pull request merged**
