### PR TITLE
Improvement for #1093 - failure listeners 

### PR DESCRIPTION
**Pull request by Bisk1**
Failure listeners will allow API users:
- run custom code in response to validation failure
- access response objects after failure
- write more advanced filter with customized post-failure actions

I also refactored existing handling of 'logging on validation failure" to be one of these listeners, the only one to be configured by default.
I think the introduced listener could be used to further improve the code by removing workarounds related to logging e.g. in ValidatableResponseOptionsImpl.specification()

Detailed description for my use case in #1093

### CODE REVIEW

**Comment by johanhaleby** [comment]
@Bisk1 Thanks a lot for the PR and I'm very sorry for the late response. I will look into this, hopefully soon!

**Comment by Bisk1** [comment]
@johanhaleby OK, looking forward to your comments

**Comment by johanhaleby** [comment]
@Bisk1 I'm so sorry for not getting back to you earlier. I've taken a look at the PR now and I think it looks very good and it's a good generalization of the "log if test failed use case" that also for better customizations.

**Comment by johanhaleby** [comment]
I'm going to move `io.restassured.internal.ResponseValidationFailureListener` out of the `internal` package though since I don't think you mean it to internal right?

**Comment by Bisk1** [comment]
@johanhaleby  Hey, I'm happy to see my PR merged and released.
Regarding your question - yes, `ResponseValidationFailureListener` should not be in `internal `package. Also sorry for late reply

**Pull request merged**
