### PR TITLE
Detailed cookie matcher introduced.

### PR DESCRIPTION
**Pull request by rafalsiwiec**
This change introduces ability for detailed cookies assertions.

### CODE REVIEW

**Comment by johanhaleby** [comment]
Nice! Thanks a lot for the contribution. But would it be possible to add an overloaded method instead of introducing a new one with different name? I.e. instead of:

```java
given().
       get("/multiCookie").
then().
      detailedCookie("cookie1", detailedCookie().maxAge(1234567));
```

it might be possible to do:

```java
given().
       get("/multiCookie").
then().
      cookie("cookie1", detailedCookie().maxAge(1234567));
```

Maybe it'll be easier to find and more intuitive for people than `detailedCookie`?

WDYT?

**Comment by rafalsiwiec** [comment]
@johanhaleby since:

```public T cookie(String cookieName, Matcher<?> expectedValueMatcher)```

method exists, we would need to be more specific and use exact matcher type - `DetailedCookieMatcher` - in the method signature.

So, instead of:

```T cookie(String cookieName, Matcher<? super Cookie> detailedCookieMatcher)```

it would be:

```T cookie(String cookieName, DetailedCookieMatcher detailedCookieMatcher)```

Initially, I thought that flexibility to use any matcher you want, for detailed cookie assertions would be useful. But since the case is rather narrow, and `DetailedCookieMatcher` provides fluent api for all properties I agree with your point.

**Comment by johanhaleby** [comment]
Thanks for the contribution, highly appreciated!

**Comment by rafalsiwiec** [comment]
Thanks for accepting this @johanhaleby :)
When do you plan to release next version?

**Comment by johanhaleby** [comment]
Dunno. There's so much stuff to do and fix but I'm short on time. Maybe I should just release a new point release soon.

**Pull request merged**
