### PR TITLE
ResponseSpecification: Don't join root and path with '.' if path starts with array indexing

### PR DESCRIPTION
**Pull request by feshbach**
This is the same bug that was fixed in #727 except for ResponseSpecificationImpl.

### CODE REVIEW

**Comment by johanhaleby** [comment]
Thanks for the PR! Could you provide a test case as well though?

**Comment by feshbach** [comment]
Sure. Where should it go? Do I need to create a new test class? Do I need to do anything to get the test to run?

**Comment by johanhaleby** [comment]
There's class called `RootPathITest`, perhaps you could add it there?

**Comment by johanhaleby** [comment]
Thanks a lot for your help!

**Pull request merged**
